### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Oluwasetemi** [wesbos/css-grid-talk#1]
![image](https://user-images.githubusercontent.com/10030028/44635844-3d1d6c00-a9a0-11e8-9c5f-6775df074b63.png)

**Comment by wesbos** [comment]
Send me a PR 😃

**Comment by Oluwasetemi** [comment]
Alright!!🆒

**Comment by Oluwasetemi** [comment]
PR sent already [✍](https://github.com/wesbos/css-grid-talk/pull/2/commits/8f9fa21183a137cbc6060e154ae55f7c7a99b8fd)
